/** Declaration file generated by dts-gen */

export declare interface ServiceCredentials {
  apikey: string;
  url: string;
  iam_apikey_name: string;
  iam_role_crn: string;
  iam_serviceid_crn: string;
}

export function getCredentialsForService(serviceTag: any, serviceLabel: any, credentials: any): any;

export function getDictionary(name: any): any;

export function getString(name: any): any;

export function init(mappingsFilePath: any): void;

export function setLogLevel(level: any): void;

